version: '3.8'

services:
  db:
    image: postgres:15
    container_name: bun-badges-db
    environment:
      POSTGRES_DB: badges
      POSTGRES_USER: badges_user
      POSTGRES_PASSWORD: badges_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U badges_user -d badges"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 