version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bun-badges-api
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NODE_ENV: production
      PORT: 7777
      DATABASE_URL: postgres://${POSTGRES_USER:-badges_user}:${POSTGRES_PASSWORD:-badges_password}@db:5432/${POSTGRES_DB:-badges}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      JWT_EXPIRY: ${JWT_EXPIRY:-15m}
      REFRESH_TOKEN_EXPIRY: ${REFRESH_TOKEN_EXPIRY:-7d}
      USE_HTTPS: ${USE_HTTPS:-false}
      TLS_CERT_FILE: ${TLS_CERT_FILE:-/app/certs/cert.pem}
      TLS_KEY_FILE: ${TLS_KEY_FILE:-/app/certs/key.pem}
      TLS_PASSPHRASE: ${TLS_PASSPHRASE:-}
    ports:
      - "${PORT:-7777}:7777"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7777/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./dist:/app/dist
      - ./drizzle:/app/drizzle
      - ./certs:/app/certs
    networks:
      - bun-badges-network

  db:
    image: postgres:15
    container_name: bun-badges-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-badges}
      POSTGRES_USER: ${POSTGRES_USER:-badges_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-badges_password}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-badges_user} -d ${POSTGRES_DB:-badges}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - bun-badges-network

volumes:
  postgres_data:

networks:
  bun-badges-network:
    driver: bridge 