name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
          
      - name: Install dependencies
        run: bun install
        
      - name: Setup CI environment
        run: cp .env.ci .env
        
      - name: Type check
        run: bun run tsc

      - name: Run linter
        run: bun run lint
        
      - name: Run unit tests
        run: bun run test:unit

      - name: Run integration tests
        run: bun run test:integration
        env:
          CI: "true"
          FORCE_MOCK_DB: "true"
          SKIP_DOCKER: "true"
          NODE_ENV: "test"

      - name: Run e2e tests
        run: bun run test:e2e
        env:
          CI: "true"
          FORCE_MOCK_DB: "true"
          SKIP_DOCKER: "true"
          NODE_ENV: "test"
      

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
          
      - name: Install dependencies
        run: bun install
        
      - name: Build
        run: bun run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/ 